### ISSUE TITLE
/v1.0/verifiableCredentials/createIssuanceRequest API not working from local 

### ISSUE THREAD

**Issue by vaibhav6464** [Azure-Samples/active-directory-verifiable-credentials-python#28]
I am trying to run the app from my company owned local machine from intrAnet. I am getting below error while trying to issue creds from API 

https://verifiedid.did.msidentity.com/v1.0/verifiableCredentials/createIssuanceRequest

Error : {'requestId': 'e354c61b4ec106e811bfa94e4dbee6f7', 'date': 'Wed, 24 Jul 2024 11:00:12 GMT', 'mscv': '24qoe4SlrN68BXAQ.1', 'error': {'code': 'badRequest', 'message': 'The request is invalid.', 'innererror': {'code': 'badOrMissingField', 'message': 'URL must be public', 'target': 'callback.url'}}}

**Comment by cljung** [comment]
You can not run Verified ID samples on localhost as it uses callbacks. You need to use ngrok locally or deploy it to something like Azure AppServices.
